name: Yield
options:
  bundleIdPrefix: com.jeremyfields
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "15.0"
  minimumXcodeGenVersion: "2.38"

packages:
  Sparkle:
    url: https://github.com/sparkle-project/Sparkle
    from: "2.6.0"

targets:
  Yield:
    type: application
    platform: macOS
    sources:
      - Yield
    resources:
      - path: Yield/Fonts
        buildPhase: resources
    dependencies:
      - package: Sparkle
        product: Sparkle
    info:
      path: Yield/Info.plist
      properties:
        CFBundleShortVersionString: "$(MARKETING_VERSION)"
        CFBundleVersion: "$(CURRENT_PROJECT_VERSION)"
        LSUIElement: true
        CFBundleDisplayName: "Yield"
        CFBundleName: Yield
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: false
          NSAllowsLocalNetworking: true
        ATSApplicationFontsPath: "."
        SUFeedURL: "https://raw.githubusercontent.com/vigetlabs/yield-app/main/appcast.xml"
        SUPublicEDKey: "qf90v1Zbq7OTVAfWHnhjzHEkvnW4juPWIgjbm/3U/P8="
        SUEnableAutomaticChecks: true
        SUScheduledCheckInterval: 86400
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.yield
        SWIFT_VERSION: "5.9"
        MACOSX_DEPLOYMENT_TARGET: "14.0"
        PRODUCT_NAME: "Yield"
        MARKETING_VERSION: "0.9.5.1"
        CURRENT_PROJECT_VERSION: "8"
        ENABLE_HARDENED_RUNTIME: true
        CODE_SIGN_IDENTITY: "Developer ID Application: Jeremy Fields (7G49Y875S8)"
        DEVELOPMENT_TEAM: 7G49Y875S8
        CODE_SIGN_STYLE: Manual
        CODE_SIGN_ENTITLEMENTS: Yield/Yield.entitlements
